# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: docker:latest

services:
  - docker:dind

stages:
- test
- build
# - secret-detection
# secret_detection:
#   stage: secret-detection
# --- Security Scans ---
include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
# --- Docker Build & Push Logic ---
variables:
  # Using the image name from your project details
  DOCKER_IMAGE: andrewixl/tierzerocode
  # This tells docker:dind to NOT generate certs and use plain TCP (port 2375)
  DOCKER_TLS_CERTDIR: ""

# Shared configuration for build jobs
.build_template: &build_configuration
  stage: build
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build -t $DOCKER_IMAGE:$TAG .
    - docker push $DOCKER_IMAGE:$TAG

# Job 1: Runs when you push to 'dev' -> tags as 'latest-dev'
build_dev:
  <<: *build_configuration
  variables:
    TAG: latest-dev
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

# Job 2: Runs when you push to 'master' -> tags as 'latest'
build_master:
  <<: *build_configuration
  variables:
    TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

# sast:
#   stage: test
