image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

variables:
  DOCKER_IMAGE: hub.awbtech.org/tierzerocode/tierzerocode
  DOCKER_TLS_CERTDIR: ""

# Shared configuration for build jobs
.build_template: &build_configuration
  stage: build
  before_script:
    - docker login hub.awbtech.org -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD"
    - docker system prune -a -f
  script:
    # --pull ensures we check for a fresh base image to avoid metadata corruption
    - docker build --pull --platform linux/amd64 -t $DOCKER_IMAGE:$TAG .
    - docker push $DOCKER_IMAGE:$TAG

# Job 1: Runs when you push to 'dev'
build_dev:
  <<: *build_configuration
  variables:
    TAG: latest-dev
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

# Job 2: Runs when you push to 'master'
build_master:
  <<: *build_configuration
  variables:
    TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"